## Default configuration for development environment.
chassis:
  app:
    name: ${APP_NAME:chassis-middleware-id-generator}
    port: ${APP_PORT:9781}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.apache.zookeeper.ClientCnxn: fatal

## Only use H2 for development environment, don's use on production!!!
## Uncomment when segment.enable is true.
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS:org.h2.Driver}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATION:classpath:/db/migration}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED:false}

## Replace for production environment.
## Uncomment when segment.enable is true.
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/id-generator?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&sessionVariables=character_set_connection=utf8mb4,character_set_client=utf8mb4
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: password01!
#  flyway:
#    enabled: true
#    locations: classpath:/db/migration

# Enable id generator or not.
id-generator:
  segment:
    enabled: ${ID_GENERATOR_SEGMENT_ENABLED:false}
  snowflake:
    enabled: ${ID_GENERATOR_SNOWFLAKE_ENABLED:false}
    zookeeper:
      host: ${ID_GENERATOR_SNOWFLAKE_ZK_HOST:127.0.0.1}
      port: ${ID_GENERATOR_SNOWFLAKE_ZK_PORT:2181}
